# Generated by Django 5.1.6 on 2025-02-24 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sess_admin_portal", "0004_employee_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                (
                    "apt_or_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sess_admin_portal.address",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sess_admin_portal.address",
            ),
        ),
        migrations.AlterField(
            model_name="programs",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sess_admin_portal.address",
            ),
        ),
        migrations.AlterField(
            model_name="regionalcenter",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sess_admin_portal.address",
            ),
        ),
    ]
