# Generated by Django 5.1.6 on 2025-02-24 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "sess_admin_portal",
            "0005_address_alter_client_address_alter_employee_address_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Appointments",
            new_name="Appointment",
        ),
        migrations.RenameModel(
            old_name="Medications",
            new_name="Medication",
        ),
        migrations.RenameModel(
            old_name="Programs",
            new_name="Program",
        ),
        migrations.AddField(
            model_name="address",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalcareteam",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sess_admin_portal.address",
            ),
        ),
    ]
